- name: Build APK
        run: |
          # تنظيف البيئة
          rm -rf build/
          rm -rf .flet/
          
          # الأمر الصحيح حسب تحديثات Flet الأخيرة:
          # نستخدم --android-permissions للصلاحيات العامة
          # ونستخدم --yes لتخطي أسئلة التثبيت
          flet build apk --yes --android-permissions android.permission.INTERNET,android.permission.WRITE_EXTERNAL_STORAGE,android.permission.READ_EXTERNAL_STORAGE --verbose
